title: Forrest Koran
email: forrest.koran@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "fkoran.github.io" # the base hostname & protocol for your site
github_username:  fkoran
paginate: 10

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title/

gems: [jekyll-paginate]

exclude: ['build.sh', 'README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']



